### ISSUE TITLE
Missing signup button in register activity

### ISSUE THREAD

**Issue by refactor-droidyy** [NJACKWinterOfCode/onRoad#37]
In Phone With small screen size, the  SignUp Button is missing.

**Comment by Priyanka-Sachan** [comment]
I am working on this issue.

**Comment by refactor-droidyy** [comment]
@Priyanka-Sachan sure, go ahead.

**Comment by thebishaldeb** [comment]
@Priyanka-Sachan update?

**Comment by PriyankaKarnati** [comment]
Hi, can I work on this too?

**Comment by refactor-droidyy** [comment]
@PriyankaKarnati since @Priyanka-Sachan is not responding so you can grab this one.

**Comment by PriyankaKarnati** [comment]
1.actually Register & login buttons are not visible during the launch of app, I am not able to see which activity is being launched after Splash activity and userType activity. 
2.I think the issue referred here is that signIn button text is not visible in RegisterActivity, this is due to same background colour and text colour of the button.

**Comment by refactor-droidyy** [comment]
@PriyankaKarnati  have a look to java files u will sure get something.
