### ISSUE TITLE
Integrate maps in the Apps

### ISSUE THREAD

**Issue by Sarthak2601** [NJACKWinterOfCode/onRoad#4]
Map should show the current location of the car booked

**Comment by Sarthak2601** [comment]
Working on it.

**Comment by sg28march** [comment]
@Sarthak2601  are you still working on it?

**Comment by sg28march** [comment]
@thebishaldeb  I think you should assign one  issue to a person  at a time because this will create equal opportunity for all . This will also help to complete project in less time. Some people have taken more then one issues and we are not getting issues to solve . Please see to it. 
And can i work on this issue?

**Comment by VARUN12KUMAR** [comment]
@sg28march yes you are right bro.

**Comment by thebishaldeb** [comment]
@sg28march  assigning it to you.

**Comment by thebishaldeb** [comment]
Update? @sg28march
